-- FLOOR 함수는 소수점 첫째 자리에서 버림하는 함수로, 주어진 숫자와 가장 근접한 작은 정수를 출력한다. 

SELECT A.CONTINENT, FLOOR(AVG(B.POPULATION))
FROM COUNTRY AS A
JOIN CITY AS B
ON A.CODE = B.COUNTRYCODE
GROUP BY A.CONTINENT

-- SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
-- FROM CITY INNER JOIN COUNTRY
-- ON CITY.COUNTRYCODE = COUNTRY.CODE
-- GROUP BY COUNTRY.CONTINENT;
