-- ORACLE

-- Q1.
-- SELECT DATETIME FROM (SELECT datetime from ANIMAL_INS order by DATETIME desc) where rownum=1
SELECT MAX(DATETIME) FROM ANIMAL_INS

-- Q2.
SELECT MIN(DATETIME) FROM ANIMAL_INS

-- Q3
SELECT COUNT(*) from ANIMAL_INS

-- Q4
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS WHERE NAME IS NOT NULL
